set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin


set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions-=m
call vundle#begin('~/vimplug')

Plugin 'fatih/vim-go'
Plugin 'majutsushi/tagbar'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'jstemmer/gotags'
" Plugin 'Valloric/YouCompleteMe'"需要python3支持
" Plugin 'SirVer/ultisnips'
Plugin 'L9'

Plugin 'othree/html5.vim'

Plugin 'hail2u/vim-css3-syntax'
Plugin 'groenewege/vim-less'
Plugin 'tpope/vim-haml'

Plugin 'pangloss/vim-javascript'
"Plugin 'kchmck/vim-coffee-script'
"Plugin 'leafgarland/typescript-vim'

" 补充一个 Vue 模板的
Plugin 'posva/vim-vue'

" HTML 助手
Plugin 'mattn/emmet-vim'

" JavaScript 补全
" Plugin 'ternjs/tern_for_vim'
"色彩高亮
Plugin 'gorodinskiy/vim-coloresque'

"匹配html标签高亮
Plugin 'gregsexton/MatchTag'
Plugin 'vim-scripts/matchit.zip'
" Plugin 'garbas/vim-snipmate'

" 重命名文件
Plugin 'danro/rename.vim'
" 创建文件夹
Plugin 'pbrisbin/vim-mkdir'
" 快速删除、修改、添加括号、引号等
Plugin 'tpope/vim-surround'
" 快速注释
Plugin 'vim-scripts/tComment'
" 快速对齐
Plugin 'godlygeek/tabular'
" 快速定位
Plugin 'Lokaltog/vim-easymotion'
" markdown实时预览
Plugin 'suan/vim-instant-markdown'


call vundle#end()

set nu
syntax enable
set ruler
set autoindent
set cursorline
set showmode
set ts=2
set sw=2
set nobackup
set expandtab
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gbk,latin1
set foldmethod=diff
au BufNewFile,BufRead *.vue setf html
syntax on
filetype plugin on

colorscheme solarized

set background=dark
set diffexpr=MyDiff()
" vim-go settings
let g:go_fmt_command = "goimports"

" YCM settings
let g:ycm_key_list_select_completion = ['', '']
let g:ycm_key_list_previous_completion = ['', '']
let g:ycm_key_invoke_completion = ''

" UltiSnips settings
let g:UltiSnipsExpandTrigger=""
let g:UltiSnipsJumpForwardTrigger=""
let g:UltiSnipsJumpBackwardTrigger=""
